name:                SPL
version:             0.1.0.0
github:              "adajed/SPL"
license:             BSD3
author:              "Adam Jedrych"
maintainer:          "adam.jedrych25@gmail.com"
copyright:           "2020 Adam Jedrych"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/adajed/SPL#readme>

dependencies:
- base >= 4.7 && < 5
- array
- transformers
- containers
- mtl
- filepath
- process

library:
  source-dirs: src

executables:
  spl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SPL
